[tool.poetry]
name = "amanuensis"
version = "2.6.2"
description = "Gen3 Portal related data"
authors = ["PCDC UChicago <lgraglia@uchicago.edu>"]
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/chicagopcdc/amanuensis"
include = [
  "NOTICE",
]

[tool.poetry.dependencies]
python = ">=3.9,<4.0"
alembic = "^1.7.7"
authlib = {git = "https://github.com/uc-cdis/authlib", rev = "v0.11_CVE_patch_v1"}
#authlib = "*" # let authutils decide which version we're using
authutils = "^6.2.2" # authutils = {git = "https://github.com/chicagopcdc/authutils.git", rev = "6.1.4"}  
bcrypt = "^3.1.4"
boto3 = "1.28.57"
botocore = ">=1.12.253"
cached_property = "^1.5.1"
cdiserrors = "<2.0.0"
cdislogging = "^1.0.0"
cdispyutils = "^2.0.1"
flask_sqlalchemy_session = "^1.1"
cryptography = ">=41.0.2"
flask = ">=2.2.3"
flask-cors = ">= 3.0.3"
flask-restful = ">=0.3.8"
email_validator = "^1.1.1"
gen3authz = "^1.5.1"
gen3cirrus = "^2.0.0"
gen3config = ">=1.1.0"
gen3users = "^0.6.0"
markdown = "^3.1.1"

# this markupsafe pin is due to an error somewhere between Python 3.9.6 and 3.9.16
markupsafe = "^2.0.1"

paramiko = "^2.6.0"
psycopg2 = "^2.8.3"
pycryptodome = "3.19.0"
PyJWT = "^2.4.0"
python_dateutil = "^2.6.1"
python-jose = "^2.0.2"
pyyaml = "5.4.1"
requests = ">=2.18.0"
retry = "^0.9.2"
sqlalchemy = "^1.3.3"
marshmallow-sqlalchemy = "0.24.2"
hubspot-api-client = "^6.0.0"
werkzeug = ">=2.2.3"
cachelib = "^0.2.0"
Flask-WTF = "^1.0.0"

html2text = "^2020.1.16"


pcdcutils = {git = "https://github.com/chicagopcdc/pcdcutils.git", rev = "0.1.3"}
# hubspotclient = {git = "https://github.com/chicagopcdc/hubspotclient.git", rev = "0.1.0"}
# userportaldatamodel = {git = "https://github.com/chicagopcdc/userPortalDataModel.git", rev = "pcdc_dev"}
hubspotclient = {git = "https://github.com/chicagopcdc/hubspotclient.git", rev = "1.0.2"}
pcdc-aws-client = {git = "https://github.com/chicagopcdc/pcdc-aws-client.git", rev = "1.2.6"}
userportaldatamodel = {git = "https://github.com/chicagopcdc/userPortalDataModel.git", rev = "1.6.2"}


[tool.poetry.dev-dependencies]
addict = "^2.2.1"
cdisutilstest = {git = "https://github.com/uc-cdis/cdisutils-test", rev = "1.0.0"}
codacy-coverage = "^1.3.11" 
coveralls = "^2.1.1"
mock = "^2.0.0"
moto = "^1.1.24"
pytest = "^3.2.3"
pytest-cov = "^2.5.1"

[tool.poetry.scripts]
fence-create = 'amanuensis.scripting.fence_create:main'


[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"